---
- hosts: stageingserver
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: nodeimage
        image: "aakash97/nodeimage:{{DOCKER_TAG}}"
        state: started
	- name: Install reqired packages
      yum:
        name: nodejs
        state: present
	- name: Install React JS package
      command: npm install -g create-react-app
      
